services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - appnet
  
  initdb:
    build:
      context: ./initdb
    depends_on:
      - sqlserver
    volumes:
      - ./sql:/scripts
    networks:
      - appnet
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
    restart: on-failure

  managerapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: managerapp
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
      - initdb
    environment:
      - CONNECTIONSTRING_DEFAULT=Server=sqlserver,1433;Database=ManejoPresupuesto;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
    networks:
      - appnet
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

volumes:
  sql_data:

networks:
  appnet: